# Generated by Django 5.2.6 on 2025-09-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
