# Generated by Django 5.2.3 on 2025-06-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='image',
        ),
        migrations.AddField(
            model_name='holiday',
            name='repetition',
            field=models.CharField(choices=[('none', 'None'), ('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='none', max_length=10),
        ),
    ]
