# Generated by Django 5.0.3 on 2025-10-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercalendar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogs',
            name='entry',
            field=models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=10),
        ),
    ]
