# Generated by Django 5.0.3 on 2025-09-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_deducted',
            field=models.BooleanField(default=True),
        ),
    ]
