# Generated by Django 5.0.3 on 2025-08-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0002_remove_leaveapprovaltimeline_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
