# Generated by Django 5.0.3 on 2025-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0003_leavetype_is_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprovalaction',
            name='action',
            field=models.CharField(choices=[('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('cancelled', 'Cancelled'), ('forwarded', 'Forwarded')], max_length=20),
        ),
    ]
