# Generated by Django 5.0.3 on 2025-08-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0003_sundayexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='go_to_clinic',
            field=models.BooleanField(default=False),
        ),
    ]
