# Generated by Django 5.0.3 on 2025-08-05 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0004_leavetype_go_to_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hrs_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
