# Generated by Django 5.0.3 on 2025-08-05 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaverequest', '0007_alter_leaverequest_days_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='days_requested',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='hrs_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
