# Generated by Django 5.0.3 on 2025-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cut_off', models.CharField(max_length=50)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_stackable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OJTPayslipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off', models.CharField(max_length=50)),
                ('regular_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowance_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nd_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_school_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_ojt_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_ojt_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rice_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nd_ot_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legal_holiday', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('satoff_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rd_ot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_pay_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_allow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rd_ot_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perfect_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OJTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50, unique=True)),
                ('allowance_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reg_nd_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reg_nd_ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reg_ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rest_ot_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('legal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sat_off_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField()),
                ('file_path', models.FileField(upload_to='payslips/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_send_to_mail', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-cutoff_date'],
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('deposit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
