# Generated by Django 5.0.3 on 2025-09-08 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowance',
            name='allowance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_types', to='finance.allowancetype'),
        ),
        migrations.AddField(
            model_name='loan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_types', to='finance.loantype'),
        ),
        migrations.AddField(
            model_name='ojtpayslipdata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savings',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='loandeduction',
            unique_together={('loan', 'cut_off')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'cutoff_date')},
        ),
    ]
