# Generated by Django 5.0.3 on 2025-07-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='amount',
        ),
    ]
