# Generated by Django 5.2.3 on 2025-07-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_payslip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='employee',
            field=models.CharField(help_text='Employee ID number', max_length=50),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='static/images/payslip/'),
        ),
    ]
