# Generated by Django 5.2.6 on 2025-09-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
