# Generated by Django 5.2.3 on 2025-07-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payslip_employee_alter_payslip_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='payslip/'),
        ),
    ]
