# Generated by Django 5.0.3 on 2025-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_savings_deposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
