# Generated by Django 5.0.3 on 2025-07-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payslip_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-cutoff_date']},
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='cutoff_from',
            new_name='cutoff_date',
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'cutoff_date')},
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='cutoff_to',
        ),
    ]
