# Generated by Django 5.2.6 on 2025-09-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_allowance_deposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
