# Generated by Django 5.0.3 on 2025-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_allowance_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='period_covered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
