# Generated by Django 5.0.3 on 2025-07-23 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payslip_employee_alter_payslip_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtpayslipdata',
            name='line_number',
        ),
    ]
