# Generated by Django 5.0.3 on 2025-12-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_allowance_period_covered'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_type', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fa-piggy-bank', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='green', help_text='Color theme: green, blue, purple, orange', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Savings Type',
                'verbose_name_plural': 'Savings Types',
                'ordering': ['savings_type'],
            },
        ),
        migrations.AddField(
            model_name='savings',
            name='savings_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_records', to='finance.savingstype'),
        ),
    ]
