# Generated by Django 5.0.3 on 2026-01-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_savings_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='is_percentage',
            field=models.BooleanField(default=False, help_text="If True, amount represents a percentage (e.g., 10 for 10%). Otherwise, it's a fixed amount."),
        ),
    ]
