# Generated by Django 5.0.3 on 2025-07-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_ojtrate_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_send_to_mail',
            field=models.BooleanField(default=False),
        ),
    ]
