# Generated by Django 5.0.3 on 2025-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('general', 'General'), ('announcement', 'Announcement'), ('approval', 'For Approval')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('module', models.CharField(default='overview', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_all', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
