# Generated by Django 5.0.3 on 2025-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
    ]
