# Generated by Django 5.0.3 on 2025-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_for_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('disapproved', 'Disapproved'), ('general', 'General'), ('announcement', 'Announcement'), ('approval', 'For Approval')], default='general', max_length=20),
        ),
    ]
