# Generated by Django 5.0.3 on 2025-08-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url',
        ),
    ]
