# Generated by Django 5.0.3 on 2025-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True),
        ),
    ]
