# Generated by Django 5.2.6 on 2025-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementreaction',
            name='emoji',
            field=models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('haha', '😄'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠')], default='like', max_length=10),
        ),
    ]
