# Generated by Django 5.0.3 on 2025-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100, unique=True, verbose_name='Line Name')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ['line_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True, unique=True)),
                ('level', models.CharField(choices=[('1', 'level-1'), ('2', 'level-2'), ('3', 'level-3')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('lines', models.ManyToManyField(related_name='departments', to='generalsettings.line')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
            },
        ),
    ]
