# Generated by Django 5.0.3 on 2025-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_line_leader',
            field=models.BooleanField(default=False, verbose_name='Has Line Leader'),
        ),
    ]
