# Generated by Django 5.2.6 on 2025-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0002_department_has_line_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_line_leader',
            field=models.BooleanField(default=False, verbose_name='Is Line Leader'),
        ),
    ]
