# Generated by Django 5.2.3 on 2025-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0002_alter_department_options_alter_line_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True, unique=True)),
                ('level', models.CharField(choices=[('1', 'level-1'), ('2', 'level-2'), ('3', 'level-3')], default='1', max_length=1)),
            ],
        ),
    ]
