# Generated by Django 5.0.3 on 2025-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(2000, '₱2,000'), (3000, '₱3,000'), (4000, '₱4,000'), (5000, '₱5,000')])),
                ('number_of_cutoff', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('employee_full_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRFRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prf_category', models.CharField(choices=[('government', 'Government Transaction'), ('banking', 'Banking and Finance'), ('hr_payroll', 'Human Resources and Payroll')], max_length=20)),
                ('prf_type', models.CharField(choices=[('pagibig_loan', 'PAG-IBIG Loan'), ('pagibig_cert_payment', 'PAG-IBIG Certificate of Payment'), ('pagibig_cert_contribution', 'PAG-IBIG Certificate of Contribution'), ('philhealth_form', 'PHILHEALTH Form'), ('sss_loan', 'SSS Loan'), ('sss_maternity', 'SSS Maternity Benefits'), ('sss_sickness', 'SSS Sickness Benefits'), ('bir_form', 'BIR Form (2316/1902)'), ('rcbc_maintenance', 'RCBC Maintenance Form'), ('bank_deposit', 'Bank Deposit'), ('payroll_adjustment', 'Payroll Adjustment'), ('id_replacement', 'ID Replacement'), ('pcoe_compensation', 'PCOE with Compensation'), ('certificate_employment', 'Certificate of Employment'), ('clearance_form', 'Clearance Form'), ('emergency_loan', 'Emergency Loan'), ('medical_loan', 'Medical Assistance Loan'), ('educational_loan', 'Educational Assistance Loan'), ('coop_loan', 'Coop Loan'), ('uniform_ppe', 'Uniform / Caps / PPE / T-shirt'), ('others', 'Others')], max_length=30)),
                ('purpose', models.TextField()),
                ('control_number', models.CharField(blank=True, max_length=50, null=True)),
                ('prf_control_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
