# Generated by Django 5.0.3 on 2025-09-08 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prfrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prf_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prfrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_prfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyloan',
            name='prf_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_loan', to='prf.prfrequest'),
        ),
    ]
