# Generated by Django 5.2.3 on 2025-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prf', '0002_remove_prfrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
