# Generated by Django 5.0.3 on 2025-08-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prf', '0003_alter_prfrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(2000, '₱2,000'), (3000, '₱3,000'), (4000, '₱4,000'), (5000, '₱5,000')])),
                ('number_of_cutoff', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('employee_full_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prf_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_loan', to='prf.prfrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
