# Generated by Django 5.0.3 on 2025-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prf', '0004_emergencyloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='prfrequest',
            name='prf_control_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
