# Generated by Django 5.0.3 on 2025-09-08 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generalsettings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Child', 'Child'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_country_code', models.CharField(default='+63', max_length=5, null=True)),
                ('address', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('Regular', 'Regular'), ('Probationary', 'Probationary'), ('OJT', 'OJT')], max_length=20)),
                ('date_hired', models.DateField()),
                ('tin_number', models.CharField(max_length=15, null=True)),
                ('sss_number', models.CharField(max_length=15, null=True)),
                ('hdmf_number', models.CharField(max_length=15, null=True)),
                ('philhealth_number', models.CharField(max_length=15, null=True)),
                ('bank_account', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generalsettings.department')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generalsettings.line')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generalsettings.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('children_names', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_background', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('birth_place', models.CharField(max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('contact_country_code', models.CharField(default='+63', max_length=5, null=True)),
                ('present_block_lot', models.CharField(blank=True, max_length=50, null=True)),
                ('present_street', models.CharField(blank=True, max_length=100, null=True)),
                ('present_barangay', models.CharField(max_length=100, null=True)),
                ('present_city', models.CharField(max_length=100, null=True)),
                ('present_province', models.CharField(max_length=100, null=True)),
                ('present_country', models.CharField(default='Philippines', max_length=100)),
                ('provincial_block_lot', models.CharField(blank=True, max_length=50, null=True)),
                ('provincial_street', models.CharField(blank=True, max_length=100, null=True)),
                ('provincial_barangay', models.CharField(max_length=100, null=True)),
                ('provincial_city', models.CharField(max_length=100, null=True)),
                ('provincial_province', models.CharField(max_length=100, null=True)),
                ('provincial_country', models.CharField(default='Philippines', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('Vocational', 'Vocational')], max_length=20)),
                ('school_name', models.CharField(max_length=200)),
                ('degree_course', models.CharField(blank=True, max_length=200, null=True)),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('honors_awards', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year_graduated', '-year_graduated', '-created_at'],
                'unique_together': {('user', 'level')},
            },
        ),
    ]
