# Generated by Django 5.2.3 on 2025-07-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='present_postal_code',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='provincial_postal_code',
        ),
    ]
