# Generated by Django 5.0.3 on 2025-09-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
