# Generated by Django 5.2.3 on 2025-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_contactperson_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
