# Generated by Django 5.2.6 on 2025-09-25 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_employmentinformation_date_hired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='innovator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovator_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
