# Generated by Django 5.0.3 on 2025-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_employmentinformation_line_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinformation',
            name='innovator',
        ),
    ]
