# Generated by Django 5.2.3 on 2025-07-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_employmentinformation_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='block_lot',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='province',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='street',
        ),
    ]
