# Generated by Django 5.2.3 on 2025-06-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.svg', null=True, upload_to='profile/'),
        ),
    ]
