# Generated by Django 5.0.3 on 2025-09-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='idnumber',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeelogin',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
