# Generated by Django 5.0.3 on 2026-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_alter_employeelogin_idnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
