# Generated by Django 5.2.3 on 2025-06-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_alter_employeelogin_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
