# Generated by Django 5.2.3 on 2025-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_alter_employeelogin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
