# Generated by Django 5.2.3 on 2025-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_employeelogin_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
    ]
