# Generated by Django 5.0.3 on 2025-09-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='static/images/survey/file-upload/%Y/%m/'),
        ),
    ]
