# Generated by Django 5.0.3 on 2025-09-08 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrouting',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingevaluation',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training.training'),
        ),
        migrations.AddField(
            model_name='evaluationrouting',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='training.trainingevaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingevaluation',
            unique_together={('training', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationrouting',
            unique_together={('evaluation', 'approver')},
        ),
    ]
