# Generated by Django 5.0.3 on 2025-09-03 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorassessment',
            name='overall_assessment',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supervisorassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisorassessment',
            name='result_and_impact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
