# Generated by Django 5.0.3 on 2025-09-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_supervisorassessment_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingevaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('supervisor_reviewed', 'Supervisor Reviewed'), ('manager_reviewed', 'Manager Reviewed'), ('participant_reviewed', 'Participant Reviewed'), ('hr_review', 'HR Review'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='draft', max_length=20),
        ),
    ]
